export const images = {
  'AD': require("../assets/images/card/DiamondDeck/AD.png"),
  '2D': require("../assets/images/card/DiamondDeck/2D.png"),
  '3D': require("../assets/images/card/DiamondDeck/3D.png"),
  '4D': require("../assets/images/card/DiamondDeck/4D.png"),
  '5D': require("../assets/images/card/DiamondDeck/5D.png"),
  '6D': require("../assets/images/card/DiamondDeck/6D.png"),
  '7D': require("../assets/images/card/DiamondDeck/7D.png"),
  '8D': require("../assets/images/card/DiamondDeck/8D.png"),
  '9D': require("../assets/images/card/DiamondDeck/9D.png"),
  '10D': require("../assets/images/card/DiamondDeck/10D.png"),
  'JD': require("../assets/images/card/DiamondDeck/JD.png"),
  'QD': require("../assets/images/card/DiamondDeck/QD.png"),
  'KD': require("../assets/images/card/DiamondDeck/KD.png"),

  'AC': require("../assets/images/card/ClubDeck/AC.png"),
  '2C': require("../assets/images/card/ClubDeck/2C.png"),
  '3C': require("../assets/images/card/ClubDeck/3C.png"),
  '4C': require("../assets/images/card/ClubDeck/4C.png"),
  '5C': require("../assets/images/card/ClubDeck/5C.png"),
  '6C': require("../assets/images/card/ClubDeck/6C.png"),
  '7C': require("../assets/images/card/ClubDeck/7C.png"),
  '8C': require("../assets/images/card/ClubDeck/8C.png"),
  '9C': require("../assets/images/card/ClubDeck/9C.png"),
  '10C': require("../assets/images/card/ClubDeck/10C.png"),
  'JC': require("../assets/images/card/ClubDeck/JC.png"),
  'QC': require("../assets/images/card/ClubDeck/QC.png"),
  'KC': require("../assets/images/card/ClubDeck/KC.png"),

  'AH': require("../assets/images/card/HeartDeck/AH.png"),
  '2H': require("../assets/images/card/HeartDeck/2H.png"),
  '3H': require("../assets/images/card/HeartDeck/3H.png"),
  '4H': require("../assets/images/card/HeartDeck/4H.png"),
  '5H': require("../assets/images/card/HeartDeck/5H.png"),
  '6H': require("../assets/images/card/HeartDeck/6H.png"),
  '7H': require("../assets/images/card/HeartDeck/7H.png"),
  '8H': require("../assets/images/card/HeartDeck/8H.png"),
  '9H': require("../assets/images/card/HeartDeck/9H.png"),
  '10H': require("../assets/images/card/HeartDeck/10H.png"),
  'JH': require("../assets/images/card/HeartDeck/JH.png"),
  'QH': require("../assets/images/card/HeartDeck/QH.png"),
  'KH': require("../assets/images/card/HeartDeck/KH.png"),

  'AS': require("../assets/images/card/SpadeDeck/AS.png"),
  '2S': require("../assets/images/card/SpadeDeck/2S.png"),
  '3S': require("../assets/images/card/SpadeDeck/3S.png"),
  '4S': require("../assets/images/card/SpadeDeck/4S.png"),
  '5S': require("../assets/images/card/SpadeDeck/5S.png"),
  '6S': require("../assets/images/card/SpadeDeck/6S.png"),
  '7S': require("../assets/images/card/SpadeDeck/7S.png"),
  '8S': require("../assets/images/card/SpadeDeck/8S.png"),
  '9S': require("../assets/images/card/SpadeDeck/9S.png"),
  '10S': require("../assets/images/card/SpadeDeck/10S.png"),
  'JS': require("../assets/images/card/SpadeDeck/JS.png"),
  'QS': require("../assets/images/card/SpadeDeck/QS.png"),
  'KS': require("../assets/images/card/SpadeDeck/KS.png"),
}