export const images = {
  '1-diamond': require("../assets/images/card/DiamondDeck/1-diamond.png"),
  '2-diamond': require("../assets/images/card/DiamondDeck/2-diamond.png"),
  '3-diamond': require("../assets/images/card/DiamondDeck/3-diamond.png"),
  '4-diamond': require("../assets/images/card/DiamondDeck/4-diamond.png"),
  '5-diamond': require("../assets/images/card/DiamondDeck/5-diamond.png"),
  '6-diamond': require("../assets/images/card/DiamondDeck/6-diamond.png"),
  '7-diamond': require("../assets/images/card/DiamondDeck/7-diamond.png"),
  '8-diamond': require("../assets/images/card/DiamondDeck/8-diamond.png"),
  '9-diamond': require("../assets/images/card/DiamondDeck/9-diamond.png"),
  '10-diamond': require("../assets/images/card/DiamondDeck/10-diamond.png"),
  '11-diamond': require("../assets/images/card/DiamondDeck/11-diamond.png"),
  '12-diamond': require("../assets/images/card/DiamondDeck/12-diamond.png"),
  '13-diamond': require("../assets/images/card/DiamondDeck/13-diamond.png"),

  '1-club': require("../assets/images/card/ClubDeck/1-club.png"),
  '2-club': require("../assets/images/card/ClubDeck/2-club.png"),
  '3-club': require("../assets/images/card/ClubDeck/3-club.png"),
  '4-club': require("../assets/images/card/ClubDeck/4-club.png"),
  '5-club': require("../assets/images/card/ClubDeck/5-club.png"),
  '6-club': require("../assets/images/card/ClubDeck/6-club.png"),
  '7-club': require("../assets/images/card/ClubDeck/7-club.png"),
  '8-club': require("../assets/images/card/ClubDeck/8-club.png"),
  '9-club': require("../assets/images/card/ClubDeck/9-club.png"),
  '10-club': require("../assets/images/card/ClubDeck/10-club.png"),
  '11-club': require("../assets/images/card/ClubDeck/11-club.png"),
  '12-club': require("../assets/images/card/ClubDeck/12-club.png"),
  '13-club': require("../assets/images/card/ClubDeck/13-club.png"),

  '1-heart': require("../assets/images/card/HeartDeck/1-heart.png"),
  '2-heart': require("../assets/images/card/HeartDeck/2-heart.png"),
  '3-heart': require("../assets/images/card/HeartDeck/3-heart.png"),
  '4-heart': require("../assets/images/card/HeartDeck/4-heart.png"),
  '5-heart': require("../assets/images/card/HeartDeck/5-heart.png"),
  '6-heart': require("../assets/images/card/HeartDeck/6-heart.png"),
  '7-heart': require("../assets/images/card/HeartDeck/7-heart.png"),
  '8-heart': require("../assets/images/card/HeartDeck/8-heart.png"),
  '9-heart': require("../assets/images/card/HeartDeck/9-heart.png"),
  '10-heart': require("../assets/images/card/HeartDeck/10-heart.png"),
  '11-heart': require("../assets/images/card/HeartDeck/11-heart.png"),
  '12-heart': require("../assets/images/card/HeartDeck/12-heart.png"),
  '13-heart': require("../assets/images/card/HeartDeck/13-heart.png"),

  '1-spade': require("../assets/images/card/SpadeDeck/1-spade.png"),
  '2-spade': require("../assets/images/card/SpadeDeck/2-spade.png"),
  '3-spade': require("../assets/images/card/SpadeDeck/3-spade.png"),
  '4-spade': require("../assets/images/card/SpadeDeck/4-spade.png"),
  '5-spade': require("../assets/images/card/SpadeDeck/5-spade.png"),
  '6-spade': require("../assets/images/card/SpadeDeck/6-spade.png"),
  '7-spade': require("../assets/images/card/SpadeDeck/7-spade.png"),
  '8-spade': require("../assets/images/card/SpadeDeck/8-spade.png"),
  '9-spade': require("../assets/images/card/SpadeDeck/9-spade.png"),
  '10-spade': require("../assets/images/card/SpadeDeck/10-spade.png"),
  '11-spade': require("../assets/images/card/SpadeDeck/11-spade.png"),
  '12-spade': require("../assets/images/card/SpadeDeck/12-spade.png"),
  '13-spade': require("../assets/images/card/SpadeDeck/13-spade.png"),
}