export enum ROUTES {
  PoseidonLogin = "PoseidonLogin",
  PoseidonLobby = "PoseidonLobby",
  PoseidonGame = "PoseidonGame",
  PoseidonAccount = "PoseidonAccount",
  PoseidonProfile = "PoseidonProfile",
  PoseidonChangePass = "PoseidonChangePass",
  PoseidonSkpRoom = "PoseidonSkpRoom",
  PoseidonSkpGame = "PoseidonSkpGame",
  PoseidonThreePicRoom = "PoseidonThreePicRoom",
  PoseidonThreePicGame = "PoseidonThreePicGame",
  PoseidonThreePicGame2 = "PoseidonThreePicGame2",
  PoseidonTnc = "PoseidonTnc",
  PoseidonPrivacy = "PoseidonPrivacy",
}
